DROP TABLE IF EXISTS `npc_to_pc_polymorph`;
CREATE TABLE `npc_to_pc_polymorph` (
  `template` int(11) NOT NULL DEFAULT '0',
  `name` varchar(200) DEFAULT NULL,
  `title` varchar(200) DEFAULT NULL,
  `class_id` int(11) NOT NULL DEFAULT '0',
  `female` int(11) NOT NULL DEFAULT '0',
  `hair_style` int(11) NOT NULL DEFAULT '0',
  `hair_color` int(11) NOT NULL DEFAULT '0',
  `face` int(11) NOT NULL DEFAULT '0',
  `name_color` int(11) NOT NULL DEFAULT '0',
  `title_color` int(11) NOT NULL DEFAULT '0',
  `noble` int(11) NOT NULL DEFAULT '0',
  `hero` int(11) NOT NULL DEFAULT '0',
  `pvp` int(11) NOT NULL DEFAULT '0',
  `karma` int(11) NOT NULL DEFAULT '0',
  `wpn_enchant` int(11) NOT NULL DEFAULT '0',
  `right_hand` int(11) NOT NULL DEFAULT '0',
  `left_hand` int(11) NOT NULL DEFAULT '0',
  `gloves` int(11) NOT NULL DEFAULT '0',
  `chest` int(11) NOT NULL DEFAULT '0',
  `legs` int(11) NOT NULL DEFAULT '0',
  `feet` int(11) NOT NULL DEFAULT '0',
  `hair` int(11) NOT NULL DEFAULT '0',
  `hair2` int(11) NOT NULL DEFAULT '0',
  `pledge` int(11) NOT NULL DEFAULT '0',
  `cw_level` int(11) NOT NULL DEFAULT '0',
  `clan_id` int(11) NOT NULL DEFAULT '0',
  `ally_id` int(11) NOT NULL DEFAULT '0',
  `clan_crest` int(11) NOT NULL DEFAULT '0',
  `ally_crest` int(11) NOT NULL DEFAULT '0',
  `rnd_class` int(11) NOT NULL DEFAULT '0',
  `rnd_appearance` int(11) NOT NULL DEFAULT '0',
  `max_rnd_enchant` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (template)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;